### ISSUE TITLE
Create Parent UI Class

### ISSUE THREAD

**Issue by bbradleyX** [bbradleyX/Group-2-Bracketeer#34]
- First UI to interact with user

Asks user if they want to make a new player, team, or tournament

Player: makes Player UI object

Tournament or Team : makes Coordinator UI object

**Comment by NusiratO** [comment]
I spent 5 days on ParentUI. Each day, I spent over 3 hours trying to work it. Wednesday, I worked over 9 hours from the start of the day to towards the around 5 o'clock. Then again around midnight.
